### ISSUE TITLE
Creating ExtendedToolTips Failed

### ISSUE THREAD

**Issue by Ezilii** [Mimonsi/cities2-extended-tooltip#6]
"Creating ExtendedToolTips failed at: System.OverflowException: Negating the minimum value of a twos complement number is invalid."

When this error occurs the type of building that is occurred over stops working. For example if it occurred while hovering over a commercial building, all commercial buildings stop showing the tooltips while other building types still work.

I hope this helps. 

Thanks for all that you do.

[LogReport_24-07-20_13-53.zip](https://github.com/user-attachments/files/16322067/LogReport_24-07-20_13-53.zip)

**Comment by Mimonsi** [comment]
Thanks for reporting this issue, @Ezilii . Did the issue occur again, or is it no longer reproducible with the latest version?
